version: "4.16.2"

services:
  mongodb:
    image: mongo
    container_name: marketstore-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_DB_NAME: MarketStore
    volumes:
      - mongodb-data:/data/db


volumes:
  mongodb-data: